pizza-consumer-web/src/net/proto.json, pizza-protobuf/address.proto, pizza-protobuf/pizza.proto
Change-Id: I2cd6d2abdf49a68b08052dd94a038c9529481037
=> feat: 修改了protobuf

pizza-consumer-web/mock/proto.json, pizza-consumer-web/src/net/proto.json, pizza-protobuf/order.proto, pizza-protobuf/pizza.proto
Change-Id: I58219af869969ad7989da46501201b2d726ae366
=> feat: change protobuf name

pizza-consumer-web/src/biz-components/Banner/index.scss, pizza-consumer-web/src/biz-components/Banner/index.tsx, pizza-consumer-web/src/biz-components/Input/index.scss, pizza-consumer-web/src/biz-components/Input/index.tsx, pizza-consumer-web/src/biz-components/PageAssets/index.tsx, pizza-consumer-web/src/pages/LoginAssets/FindPW/index.scss, pizza-consumer-web/src/pages/LoginAssets/FindPW/index.tsx, pizza-consumer-web/src/pages/LoginAssets/LoginPW/index.tsx, pizza-consumer-web/src/pages/LoginAssets/SetPW/index.scss, pizza-consumer-web/src/pages/LoginAssets/SetPW/index.tsx, pizza-consumer-web/src/pages/LoginAssets/index.tsx, pizza-consumer-web/src/store/reducers/page/login/action.ts, pizza-consumer-web/src/store/reducers/page/login/reducer.ts, pizza-consumer-web/src/ui/base.scss, pizza-consumer-web/src/ui/base.ts, pizza-consumer-web/src/utils/time.ts
Change-Id: I403fe83708853ea60f4621c15b98ec1ddaba371c
=> feat: 添加login页面

pizza-consumer-web/mock/proto.json, pizza-consumer-web/src/net/proto.json, pizza-consumer-web/src/pages/MainAssets/Main/Shopping/index.scss, pizza-consumer-web/src/pages/MainAssets/Main/Shopping/index.tsx, pizza-protobuf/address.proto
Change-Id: I74ca1afab122e7c8c069ab8d96a8ca8a146936dc
=> fix: address.proto express -> tag

pizza-consumer-web/mock/entity/Address.js, pizza-consumer-web/mock/server.js, pizza-consumer-web/mock/utils/log.js, pizza-consumer-web/src/entity/Address/index.ts, pizza-consumer-web/src/entity/Order/index.ts, pizza-consumer-web/src/pages/MainAssets/Main/OrderList/index.tsx, pizza-consumer-web/src/pages/MainAssets/Main/index.tsx, pizza-consumer-web/src/pages/MainAssets/OrderDetail/index.scss, pizza-consumer-web/src/pages/MainAssets/OrderDetail/index.tsx, pizza-consumer-web/src/pages/MainAssets/index.tsx, pizza-consumer-web/src/store/reducers/page/main/reducer.ts, pizza-protobuf/order.proto
Change-Id: Ic0f80d915ca8dba1cd055d6183f78a79ec2cbe35
=> feat: 添加了订单详情页面

.gitignore, pizza-consumer-web/src/biz-components/Banner/index.tsx, pizza-consumer-web/src/biz-components/Footer/index.tsx, pizza-consumer-web/src/pages/LoginAssets/index.tsx, pizza-consumer-web/src/pages/MainAssets/Main/Me/index.tsx, pizza-consumer-web/src/pages/MainAssets/OrderDetail/index.tsx, pizza-protobuf/order.proto
1. 添加fetchPhone接口
2.
Change-Id: I2856e1d8909859587b9ccc619afb6babbbc3e9dd
=> feat: 修改order接口

pizza-consumer-web/mock/proto.json, pizza-consumer-web/src/net/proto.json, pizza-consumer-web/src/pages/MainAssets/Main/Shopping/index.scss, pizza-consumer-web/src/pages/MainAssets/Main/Shopping/index.tsx, pizza-consumer-web/src/pages/MainAssets/Main/index.tsx, pizza-consumer-web/src/pages/MainAssets/Pay/index.scss, pizza-consumer-web/src/pages/MainAssets/Pay/index.tsx, pizza-consumer-web/src/pages/MainAssets/Settlement/index.scss, pizza-consumer-web/src/pages/MainAssets/Settlement/index.tsx, pizza-consumer-web/src/pages/MainAssets/index.tsx, pizza-consumer-web/src/store/reducers/page/main/reducer.ts, pizza-protobuf/user.proto
Change-Id: I9b52f57a6375dd2272229fd890d3c2642acf31bb
=> feat: 添加了支付页面

pizza-protobuf/address.proto, pizza-protobuf/order.proto, pizza-protobuf/user.proto
Change-Id: I995cae438ac8158c8cbd80b939d14bd5770f3e68
=> feat: 修改接口method和url

pizza-consumer-web/.gitignore
Change-Id: I7f1aada98e1b508ea3333a60f3115d001adf6899
=> feat: 将protobuf生成文件从git中移除

pizza-consumer-web/mock/routers/router-fetch-menu.js, pizza-consumer-web/src/pages-pc/LoginAssets/Register/index.scss, pizza-consumer-web/src/pages-pc/LoginAssets/Register/index.tsx, pizza-consumer-web/src/pages-pc/LoginAssets/index.tsx, pizza-consumer-web/src/pages-pc/MainAssets/Menu/index.scss, pizza-consumer-web/src/pages-pc/MainAssets/Menu/index.tsx, pizza-consumer-web/src/pages-pc/MainAssets/Order/index.scss, pizza-consumer-web/src/pages-pc/MainAssets/Order/index.tsx, pizza-consumer-web/src/pages-pc/MainAssets/index.scss, pizza-consumer-web/src/pages-pc/MainAssets/index.tsx, pizza-consumer-web/webpack.dev.js, pizza-consumer-web/yarn.lock
Change-Id: I2d1fb034bd0e8448f75d4d2c86d869ae505950f3
=> fix: easy change

pizza-consumer-web/server/proto.json, pizza-consumer-web/server/routers/router-add-address.js, pizza-consumer-web/server/routers/router-update-address.js, pizza-consumer-web/src/biz-components/Input/index.tsx, pizza-consumer-web/src/biz-components/PageAssets/index.tsx, pizza-consumer-web/src/net/api-add-address/index.ts, pizza-consumer-web/src/net/api-fetch-orders/index.ts, pizza-consumer-web/src/net/api-update-address/index.ts, pizza-consumer-web/src/net/command.ts, pizza-consumer-web/src/net/config.ts, pizza-consumer-web/src/pages-mobile/MainAssets/Address/index.scss, pizza-consumer-web/src/pages-mobile/MainAssets/Address/index.tsx, pizza-consumer-web/src/pages-mobile/MainAssets/AddressEdit/index.scss, pizza-consumer-web/src/pages-mobile/MainAssets/AddressEdit/index.tsx, pizza-consumer-web/src/pages-mobile/MainAssets/Main/Me/index.tsx, pizza-consumer-web/src/pages-mobile/MainAssets/Main/Menu/index.tsx, pizza-consumer-web/src/pages-mobile/MainAssets/Main/OrderList/index.tsx, pizza-consumer-web/src/pages-mobile/MainAssets/Main/index.tsx, pizza-consumer-web/src/pages-mobile/MainAssets/index.tsx, pizza-consumer-web/src/services/api-add-address.ts, pizza-consumer-web/src/services/api-update-address.ts, pizza-protobuf/address.proto
Change-Id: I53b722a8fd99ac3adc838b024f127386e1d2a59e
=> feat: 整理了几个fetch api

pizza-consumer-web/server/routers/router-cancel-order.js, pizza-consumer-web/server/routers/router-fetch-order.js, pizza-consumer-web/server/routers/router-send-order.js, pizza-consumer-web/src/net/api-cancel-order/index.ts, pizza-consumer-web/src/net/api-fetch-menu/index.ts, pizza-consumer-web/src/net/api-fetch-order/index.ts, pizza-consumer-web/src/net/api-send-order/index.ts, pizza-consumer-web/src/net/command.ts, pizza-consumer-web/src/net/config.ts, pizza-consumer-web/src/pages-mobile/MainAssets/Address/index.tsx, pizza-consumer-web/src/pages-mobile/MainAssets/Main/index.tsx, pizza-consumer-web/src/pages-mobile/MainAssets/OrderDetail/index.tsx, pizza-consumer-web/src/pages-mobile/MainAssets/Pay/index.scss, pizza-consumer-web/src/pages-mobile/MainAssets/Pay/index.tsx, pizza-consumer-web/src/pages-mobile/MainAssets/Settlement/index.tsx, pizza-consumer-web/src/pages-mobile/MainAssets/index.tsx, pizza-consumer-web/src/services/api-cancel-order.ts, pizza-consumer-web/src/services/api-fetch-menu.ts, pizza-consumer-web/src/services/api-fetch-order.ts, pizza-consumer-web/src/services/api-send-order.ts, pizza-consumer-web/src/store/reducers/common/action.ts, pizza-consumer-web/src/store/reducers/common/reducer.ts, pizza-protobuf/order.proto
Change-Id: Iabf0597c1279308e871be3027d05b345b6952de3
=> optimzer: 对mobile的接口进行了优化调整

pizza-consumer-web/.gitignore, pizza-consumer-web/package.json, pizza-consumer-web/src/entry.tsx, pizza-consumer-web/src/pages-mobile/MainAssets/Address/index.scss, pizza-consumer-web/src/pages-mobile/MainAssets/Main/Shopping/index.scss, pizza-consumer-web/src/pages-mobile/MainAssets/Settlement/index.scss, pizza-consumer-web/src/utils/device.ts, pizza-consumer-web/webpack.dev.js, pizza-consumer-web/webpack.prod.js, pizza-consumer-web/yarn.lock
Change-Id: I26acceb17f14522b778d929be16970303cf63974
=> feat: 修改了部分UI

pizza-consumer-web/src/App.tsx, pizza-consumer-web/src/pages-mobile/MainAssets/Main/Me/index.tsx, pizza-consumer-web/src/services/api-fetch-address.ts, pizza-consumer-web/src/services/api-fetch-menu.ts, pizza-consumer-web/src/services/api-fetch-order.ts, pizza-consumer-web/src/services/api-fetch-orders.ts, pizza-consumer-web/src/services/api-fetch-user.ts, pizza-consumer-web/src/services/api-logout.ts, pizza-consumer-web/src/utils/db.ts, pizza-consumer-web/src/utils/log.ts, pizza-consumer-web/webpack.prod.js
Change-Id: Ie2b7563fca4b73dcaf87723452d2bbe1beffd189
=> feat: 添加了离线缓存

pizza-web-performance/src/electron-main/config.js, pizza-web-performance/src/electron-main/modules/util/timeout.js, pizza-web-performance/src/electron-main/modules/webLoader/event.js, pizza-web-performance/src/electron-main/modules/webLoader/forked.js, pizza-web-performance/src/electron-main/modules/webLoader/middlewares.js, pizza-web-performance/src/electron-render/pages/Main/index.scss, pizza-web-performance/src/electron-render/pages/Main/index.tsx, pizza-web-performance/src/electron-render/utils/event.ts
Change-Id: I3cd6746066bc1681b74190e54c00a9f2b078a589
=> feat: 完善了自动化测试框架

pizza-consumer-web/server/net.js, pizza-consumer-web/server/proto.json, pizza-consumer-web/server/routers/router-send-verification.js, pizza-consumer-web/src/pages-mobile/LoginAssets/Register/index.tsx, pizza-consumer-web/src/pages-mobile/MainAssets/Main/index.tsx, pizza-consumer-web/src/pages-pc/MainAssets/index.tsx, pizza-consumer-web/src/services/api-fetch-user.ts, pizza-consumer-web/src/services/api-login.ts, pizza-consumer-web/src/services/api-register.ts, pizza-protobuf/user.proto
Change-Id: I99eb5c187e6fdc9272105445dadfbde2d34cdd8e
=> feat: 与后端联调

pizza-consumer-web/server/proto.json, pizza-consumer-web/src/App.tsx, pizza-consumer-web/src/pages-pc/LoginAssets/Login/index.tsx, pizza-consumer-web/src/pages-pc/LoginAssets/Register/index.tsx, pizza-consumer-web/src/pages-pc/MainAssets/MenuPage/Menu/Shopping/index.tsx, pizza-consumer-web/src/pages-pc/MainAssets/MenuPage/Menu/index.tsx, pizza-consumer-web/src/pages-pc/MainAssets/MenuPage/Pay/index.tsx, pizza-consumer-web/src/pages-pc/MainAssets/MenuPage/index.tsx, pizza-consumer-web/src/pages-pc/MainAssets/Order/OrderDetail/index.tsx, pizza-consumer-web/src/pages-pc/MainAssets/index.tsx
Change-Id: I756bdcb1cda02d2386710ba82e9f93e01540ef89
=> feat: 联调pc与后端

pizza-consumer-web/package.json, pizza-consumer-web/server/proto.json, pizza-consumer-web/server/routers/router-pay-order.js, pizza-consumer-web/src/App.tsx, pizza-consumer-web/src/index.html, pizza-consumer-web/src/net/api-pay-order/index.ts, pizza-consumer-web/src/net/command.ts, pizza-consumer-web/src/net/config.ts, pizza-consumer-web/src/pages-mobile/MainAssets/Pay/index.tsx, pizza-consumer-web/src/pages-mobile/MainAssets/index.tsx, pizza-consumer-web/src/pages-mobile/PaySuccess/index.tsx, pizza-consumer-web/src/pages-mobile/index.ts, pizza-consumer-web/src/pages-pc/MainAssets/index.tsx, pizza-consumer-web/src/pages-pc/PaySuccess/index.tsx, pizza-consumer-web/src/pages-pc/index.ts, pizza-consumer-web/src/services/api-fetch-user.ts, pizza-consumer-web/src/services/api-pay-order.ts, pizza-consumer-web/src/store/reducers/common/action.ts, pizza-consumer-web/src/store/reducers/common/reducer.ts, pizza-protobuf/order.proto
Change-Id: I5a7cf774a165dbf73b360fffd4b0fb76baa1ecce
=> feat: 添加了app对支付宝的支持

pizza-consumer-web/src/net/base.ts
Change-Id: Iee95834dc67da4beb1f484c1b4e246984090ae52
=> fix: tslint error

pizza-consumer-web/server/server.js
Change-Id: I29de77e037d00dea6b20acd3713c7527e50bab9e
=> fix: ipv6 => ipv4

pizza-consumer-web/src/pages-pc/LoginAssets/Login/index.tsx, pizza-consumer-web/src/pages-pc/MainAssets/MenuPage/Menu/index.tsx, pizza-consumer-web/src/pages-pc/MainAssets/index.tsx, pizza-web-performance/src/electron-render/pages/Main/index.scss, pizza-web-performance/src/electron-render/pages/Main/index.tsx
Change-Id: I5477981c391e7b064972f07d50b6391e275d856e
=> feat: 添加pc验证码，优化逻辑

pizza-consumer-web/server/entity/Order.js, pizza-consumer-web/server/routers/router-fetch-orders.js, pizza-consumer-web/src/net/base.ts
Change-Id: I93f91cdf1f4718b306db598fefff322dbe597a6b
=> fix: 订单查询接口问题

pizza-consumer-web/src/pages-pc/MainAssets/Order/index.tsx, pizza-consumer-web/src/pages-pc/MainAssets/index.tsx
Change-Id: I6066eac34c7cdfe49feb50698a04e1cf8428a138
=> fix: pc订单页面fetchOrders和fetchAddress不准的问题

pizza-consumer-web/src/pages-mobile/LoginAssets/index.tsx, pizza-consumer-web/src/pages-mobile/MainAssets/Address/index.tsx, pizza-consumer-web/src/pages-mobile/MainAssets/Main/OrderList/index.tsx, pizza-consumer-web/src/pages-mobile/MainAssets/Main/index.tsx, pizza-consumer-web/src/pages-pc/LoginAssets/index.tsx, pizza-consumer-web/src/pages-pc/MainAssets/MenuPage/Pay/index.tsx, pizza-consumer-web/src/pages-pc/MainAssets/Order/OrderList/index.tsx, pizza-consumer-web/src/pages-pc/MainAssets/Order/index.tsx, pizza-consumer-web/src/pages-pc/MainAssets/index.tsx, pizza-consumer-web/src/services/api-logout.ts, pizza-consumer-web/src/store/reducers/entity/addresses/action.ts, pizza-consumer-web/src/store/reducers/entity/addresses/reducer.ts, pizza-consumer-web/src/store/reducers/entity/orders/action.ts, pizza-consumer-web/src/store/reducers/entity/orders/reducer.ts, pizza-consumer-web/src/store/reducers/entity/pizzas/action.ts, pizza-consumer-web/src/store/reducers/entity/pizzas/reducer.ts, pizza-consumer-web/src/store/reducers/entity/user/action.ts, pizza-consumer-web/src/store/reducers/entity/user/reducer.ts
Change-Id: I414a09c10b89897ce68c0b2d069a7924b6f3fbdf
=> fix: 修改了从支付页面返回获取不到address的问题，优化了登录和注册

pizza-consumer-web/src/net/base.ts
Change-Id: I39a33bf30d5d714c8c356ee247bc6681f7254224
=> fix: BASE_URL error

pizza-consumer-web/server/routers/router-fetch-order.js, pizza-consumer-web/src/services/api-fetch-phone.ts
Change-Id: I3b4a50d037c6e3631dd8bd023ade4e3fd6d92644
=> fix: 订单状态错误
